spring:
  data:
    elasticsearch:
      cluster-name: ${chzy.elasticsearch.cluster-name}
      cluster-nodes: ${chzy.elasticsearch.cluster-nodes}
      repositories:
        enabled: true

chzy:
  swagger:
    enabled: true
    title: 日志中心
    description: 日志中心接口文档
    version: 1.0
    base-package: com.central.log.controller