server:
  port: 11001

spring:
  profiles:
    active: sharding-databases
  application:
    name: sharding-jdbc-demo

chzy:
  datasource:
    ip: 47.100.192.63
    username: root
    password: LCode1986.

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sharding.demo.model
  global-config:
    db-config:
      id-type: ID_WORKER